# Generated by Django 5.2.17 on 2026-08-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
        migrations.AddField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('feature', 'New Feature'), ('bug', 'Bug / Issue'), ('course_content', 'Course Content')], default='general', max_length=20),
        ),
    ]
