# Generated by Django 5.2.17 on 2026-08-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='quiz_correct',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='quiz_wrong',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
