# Generated by Django 5.2.17 on 2026-08-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_quizoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
