# Generated by Django 5.2.17 on 2026-08-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_admin_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_used',
            field=models.BooleanField(default=False),
        ),
    ]
